Feature/lobster version flag for tools
bmw-software-engineering/lobster pull request #129
Opened 2024-11-22 11:41 UTC by kedarnn

2024-11-28 08:02 UTC, mugdhadhole1 commented on lobster/version.py
> +    Returns - None
```suggestion
    Returns - Nothing
```

2024-11-28 11:35 UTC, mugdhadhole1 requested changes
`-v` and `--version`
command runs but the tool version is not printed as output

2024-11-28 11:56 UTC, mugdhadhole1 requested changes
While I check the version for Lobster-cpp tool, it does show the version, but it asks for mandatory arguments as input to the tool

2024-11-28 12:11 UTC, kedarnn commented
Have added support for all the missing tools.

2024-11-29 09:42 UTC, phiwuu reviewed
Please update the `CHANGELOG.md`

2024-12-10 07:09 UTC, mugdhadhole1 approved these changes

2024-12-10 07:21 UTC, merged