LOBSTER-Cpptest tool to use configuration files
bmw-software-engineering/lobster pull request #140
Opened 2024-12-05 07:40 UTC by SurajBDeore

- Replaced command-line arguments with a YAML-based configuration file for improved usability and maintainability.
- Simplifies parameter management and enhances readability.

2024-12-11 12:51 UTC, mugdhadhole1 reviewed
The markers accept @ as a parameter and error is not handled

```
other_tests.lobster:
    markers: [@]

    kind: ""
```

2024-12-11 13:19 UTC, SurajBDeore commented
> The markers accept @ as a parameter and error is not handled
> 
> ```
> other_tests.lobster:
>     markers: [@]
> 
>     kind: ""
> ```
json is invalid, please try with double quote then it will work properly

2024-12-12 05:03 UTC, phiwuu requested changes
This is a breaking change. Let's build a new release first, and merge afterwards.

2024-12-17 11:11 UTC, phiwuu approved these changes

2024-12-17 11:13 UTC, merged