Coverage integration test for requirements
bmw-software-engineering/lobster pull request #152
Opened 2024-12-10 15:19 UTC by TannazVhdBMWExt

2025-01-29 11:18 UTC, phiwuu requested changes

2025-01-29 11:18 UTC, phiwuu commented on tests-system/lobster-cpptest/rbt-invalid-source-input-file-paths/invalid-directory-input-scenario/expected-output/output.lobster
1. Why did you delete the `.gitkeep` file?
2. Why is the expected LOBSTER output file empty?

2025-01-29 11:28 UTC, phiwuu requested changes

2025-01-29 11:28 UTC, phiwuu commented on tests-integration/projects/coverage-half/Makefile
> +	@lobster-html-report
calling `lobster-html-report` is not necessary for this test

2025-01-29 11:28 UTC, phiwuu commented on tests-integration/projects/coverage-half/Makefile
> +	@lobster-online-report
remove `lobster-online-report`, because it is not important to test the coverage computation

2025-01-29 11:28 UTC, phiwuu commented on tests-integration/projects/coverage-half/Makefile
> +	@cp report.lobster report.reference_output
use https://github.com/bmw-software-engineering/lobster/blob/36d8dc79fa8dd0c90d2ada83fac93e23e2487387/tests-integration/projects/filter/Makefile#L23-L28 instead

2025-01-29 11:28 UTC, phiwuu commented on tests-integration/projects/coverage-mix/Makefile
see comments in above Makefile

2025-01-29 11:28 UTC, phiwuu commented on tests-integration/projects/coverage-zero/Makefile
see comments in above Makefile

2025-01-29 11:28 UTC, phiwuu commented on tests-integration/projects/coverage/Makefile
see comments in above Makefile

2025-02-03 12:05 UTC, TannazVhdBMWExt commented on tests-system/lobster-cpptest/rbt-invalid-source-input-file-paths/invalid-directory-input-scenario/expected-output/output.lobster
It came automatically from vispiron forked branch (I did not do these task intentionally). I replaced them with the current version of this repo.

2025-02-05 06:04 UTC, kedarnn commented on tests-integration/projects/coverage-mix/Makefile
> +	fi
Same as https://github.com/bmw-software-engineering/lobster/pull/152/files#r1942289849

2025-02-05 06:04 UTC, kedarnn commented on tests-integration/projects/coverage-zero/Makefile
> +	fi
Same as https://github.com/bmw-software-engineering/lobster/pull/152/files#r1942289849

2025-02-05 06:05 UTC, kedarnn commented on tests-integration/projects/coverage/Makefile
> +	fi
https://github.com/bmw-software-engineering/lobster/pull/152/files#r1942289849

2025-02-05 07:05 UTC, mugdhadhole1 commented on tests-integration/projects/coverage/example.rsl
> +package coverage_example
Package names in the rsl files are same and it shows the following error message

duplicate definition, previous definition at tests-integration/projects/coverage-half/example.rsl:1

2025-02-05 07:06 UTC, mugdhadhole1 commented on tests-integration/projects/coverage-zero/example.rsl
> +package coverage_example
same as https://github.com/bmw-software-engineering/lobster/pull/152/files#r1942343472

2025-02-05 09:18 UTC, phiwuu requested changes

2025-02-05 09:18 UTC, phiwuu commented on tests-integration/projects/coverage-mix/lobster.conf
> +   requires: "Test Requirements";
Why did you add the `requires` keyword here? Since "Test Requirements" already use `trace to: "Software Requirements";` it will not impact the tool behavior. Or was the idea to test exactly that the statement has no impact?

2025-02-05 09:49 UTC, phiwuu requested changes

2025-02-05 09:49 UTC, phiwuu commented on tests-integration/projects/coverage-mix/testreq_example.trlc
> +   just_up = "needed"
Why do you give a justification in this test, while adding a link to `requirement_d` at the same time?

2025-02-05 10:25 UTC, phiwuu requested changes

2025-02-05 10:25 UTC, phiwuu commented on tests-integration/projects/coverage-mix/report.reference_output
> +      "coverage": 100.0
The `requirement_d` is not linked to any requirement from level "System Requirements", but the tracing policy enforces that through `trace to`. As stated above, the `requires` keyword apparently removes this strict condition, which is a bug. Please do not use `requires` in the tests, and set the expected coverage to `0` here.

2025-02-07 11:47 UTC, phiwuu commented on tests-integration/projects/coverage/example.rsl
> +package coverage_example
Just for clarification: it is okay to have duplicates across different test cases. But if you use the TRLC extension for VSCode, and if it scans the whole repository, then it will complain about duplicated definitions.

2025-02-07 12:06 UTC, phiwuu requested changes

2025-02-07 12:06 UTC, phiwuu commented on tests-integration/projects/coverage-mix/example.rsl
> +package coverage_half_example
The test case is called `coverage-mix`, not `coverage_half_example`. It is very confusing to give the TRLC package the name of a different test case.

2025-02-07 12:06 UTC, phiwuu commented on tests-integration/projects/coverage-mix/lobster.conf
> +   trace to: "Software Requirements";
It is very confusing to derive system requirements from software requirements. Please consider to either switch the names, or use made-up names like "Apple", "Banana", etc. instead!

2025-02-07 12:06 UTC, phiwuu commented on tests-integration/projects/coverage-mix/example.rsl
> +  derived_from optional System_Requirement  [1 .. *]
The one requirement in `softreq_example.trlc` does not use the attribute `derived_from` at all. It can be removed.
Furthermore, the `example.rsl` demands that the breakdown happens the other way around, from software requirements to system requirements.
Please keep the test as simple as possible, and don't pollute it with configuration aspects that are not important to the test.

2025-03-18 14:35 UTC, phiwuu approved these changes

2025-03-18 14:39 UTC, merged

2025-03-18 14:48 UTC, phiwuu commented on tests-integration/projects/coverage-mix/lobster.conf
> +   trace to: "Software Requirements";
This comment will be implemented in https://github.com/bmw-software-engineering/lobster/pull/241

2025-03-18 14:55 UTC, phiwuu commented on tests-integration/projects/coverage-mix/example.rsl
> +package coverage_half_example
This comment will be implemented in https://github.com/bmw-software-engineering/lobster/pull/241

2025-03-18 15:25 UTC, phiwuu commented on tests-integration/projects/coverage-mix/example.rsl
> +  derived_from optional System_Requirement  [1 .. *]
This comment will be implemented in https://github.com/bmw-software-engineering/lobster/pull/241