improve accessibility in LOBSTER html report
bmw-software-engineering/lobster pull request #34
Opened 2024-04-22 12:55 UTC by ankushsonare1

improve accessibility in LOBSTER report: HTML report #26

As a maintainer of the LOBSTER tool

I change prominent colours.

So that visually impaired people (color blindness) can distinguish easily between error and success

2024-06-21 13:17 UTC, mugdhadhole1 commented
Colors seems ok
Ok to merge

2024-06-24 08:47 UTC, florianschanda commented
I suggest to add a command-line flag to do this, or even a javascript enabled toggle in the document itself.

Changing the default colours for everyone is not intuitive.

2024-06-24 08:48 UTC, florianschanda commented
I suggest to add a command-line flag to do this, or even a javascript enabled toggle in the document itself.

Changing the default colours for everyone is not intuitive.

2024-06-26 08:26 UTC, christophkloeffel requested changes
please remove report.lobster and lobster_report.html

2024-06-26 08:51 UTC, phiwuu requested changes

2024-06-26 08:51 UTC, phiwuu commented on report.lobster
> +{
Please don't add this file. I guess it is a mistake?

2024-06-26 08:51 UTC, phiwuu commented on lobster_report.html
> +<!DOCTYPE html>
Please don't add this file. I guess it is a mistake?

2024-06-26 08:51 UTC, phiwuu commented
The new images look very nice.

2024-06-26 15:26 UTC, phiwuu commented
Please clarify the copyright of the new icons. If we are OK to use them, then please update the colours as follows:

1. use a darker green instead of light green, e.g. `b2e1b2`
2. change red to purple, e.g. `ffb2ff`
3. keep the gray as is

2024-06-27 08:21 UTC, florianschanda submitted a review, later dismissed
I suggest to add a command-line flag to do this, or even a javascript enabled toggle in the document itself.

Changing the default colours for everyone is not intuitive.

2024-06-27 08:27 UTC, phiwuu commented
I saw your comment, but I don't get the point. What do you mean with "not intuitive"?
The color changes are minimal, but solve the issue for visually impaired people. Adding a command-line flag or javascript is much more effort compared to changing the colors. We want to close this issue and move on.

2024-07-23 11:28 UTC, ankushsonare1 commented
I have check new svg icons its not copyright.

2024-07-25 07:59 UTC, florianschanda commented
Traffic light colours are universally clear.
The proposed colours are not - you need to add a legend at the very least.

2024-07-25 08:13 UTC, phiwuu commented
> Traffic light colours are universally clear. The proposed colours are not - you need to add a legend at the very least.

That's a fair point.

2024-07-25 17:00 UTC, florianschanda commented
I would still strongly argue for a command-line option if a live, in document option using JS is too hard to do. It won't be too hard to do given how we bake in the style sheet anyway.

2024-08-05 08:00 UTC, phiwuu requested changes

2024-08-05 08:00 UTC, phiwuu commented on lobster/tools/core/html_report.py
> +        "background-color" : "#b2e1b2",
please add a switch case here, as suggested by @florianschanda

2024-08-05 08:00 UTC, phiwuu commented on lobster/tools/core/html_report.py
> +        "background-color" : "#ffb2ff",
and here as well

2024-09-11 13:38 UTC, christophkloeffel requested changes

2024-09-11 13:38 UTC, christophkloeffel commented on lobster/tools/core/html_report.py
> +    ap.add_argument("--color_blind",
please use flag `--color-blind`

2024-09-11 13:38 UTC, christophkloeffel commented on lobster/tools/core/html_report.py
> +                        help="Enable color blind mode")
be more specific in the help message: 
something like "uses a color palette with a higher contrast"

2024-09-11 13:41 UTC, christophkloeffel commented
please also create an entry in the changelog

2024-09-11 16:01 UTC, christophkloeffel approved these changes

2024-09-13 13:18 UTC, phiwuu approved these changes

2024-09-13 13:19 UTC, merged