Add integration tests to ci
bmw-software-engineering/lobster pull request #85
Opened 2024-09-30 15:07 UTC by DiFerMa

2024-10-04 10:13 UTC, phiwuu reviewed
I believe the `MAKEFILE` needs an update since the introducion of `lobster-cpptest`.
Please have a look at https://github.com/bmw-software-engineering/lobster/blob/dda6fda8464fda00e9b2ae4fede9cde76674bd9c/Makefile#L25-L33 and add the following line:
```
make -C packages/lobster-cpptest
```

2024-10-04 14:34 UTC, christophkloeffel requested changes

2024-10-04 14:34 UTC, christophkloeffel commented on .github/workflows/ci.yml
> +          python3 -m pip install -r requirements_dev.txt --break-system-packages
```suggestion
          python3 -m pip install --upgrade pip
          python3 -m pip install -r requirements_dev.txt
```

2024-10-04 14:34 UTC, christophkloeffel commented on .github/workflows/ci.yml
> +          python3 -m pip install -r requirements_dev.txt --break-system-packages
since we are installing python explicitly via GitHub action there is no need for this argument to be present

2024-10-08 14:06 UTC, christophkloeffel commented
CI fails because of #89

2024-10-12 10:36 UTC, christophkloeffel commented
will be replaced by #96

2024-10-12 10:37 UTC, closed without merging